services:
  - type: web
    name: lightroom-preset-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CLARIFAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
